# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:   # 👈 allows API/manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "its ok"
